### ISSUE TITLE
Installation problem (not a directory)

### ISSUE THREAD

**Issue by yw5aj** [svnpenn/velour#101]
Hi Steven,

I got into the following problem during installation:

```
shwang@SJC-PRE-16-5301 ~
$ cd velour/

shwang@SJC-PRE-16-5301 ~/velour
$ ls
check    install.sh  libhtml.awk  libm.awk  libs.awk    license.md
contrib  liba.awk    libio.awk    libn.awk  libt.awk    readme.md
doc      libh.awk    libk.awk     libo.awk  liburi.awk  velour

shwang@SJC-PRE-16-5301 ~/velour
$ ./install.sh
'/usr/local/bin/velour' -> '/home/shwang/velour/velour'
ln: target '/usr/local/share' is not a directory
```

Could you please help?

Thanks,
Shawn

**Comment by svnpenn** [comment]
Sorry, but i cant repro this. the current incarnation of the install script:

https://github.com/svnpenn/velour/blob/a8f93a30598d3ec591f83ddceab6b0907883d4bf/install.sh#L8-L9

does a "mkdir -p" on the directory in question:

~~~
-p, --parents
  no error if existing, make parent directories as needed
~~~

so i cant see how the problem would be occuring. if **you** can explain it, or
if you can help me to repro i will reopen - cheers

**Comment by svnpenn** [comment]
whoops - i see the error - one sec

**Comment by svnpenn** [comment]
ok should be working now - my bad

**Comment by yw5aj** [comment]
It works! Thank you Steven.
